-- AlterTable
ALTER TABLE "pac_product" ALTER COLUMN "gatId1" DROP DEFAULT,
ALTER COLUMN "gatId2" DROP DEFAULT,
ALTER COLUMN "gatId3" DROP DEFAULT,
ALTER COLUMN "gatId4" DROP DEFAULT,
ALTER COLUMN "gatId5" DROP DEFAULT;
